services:
  mongo:
    image: mongo:6
    container_name: lms-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: ./backend
    container_name: lms-api
    restart: always
    environment:
      - MONGO_URL=mongodb://mongo:27017/lmsdb
      - JWT_SECRET=supersecret
      - PORT=8080
    ports:
      - "8081:8080"   # ✅ Changed host port to 8081
    depends_on:
      - mongo

  web:
    build: ./frontend
    container_name: lms-web
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  mongo_data:
